services:
  traefik:
    image: "traefik:v3.5.2"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - haproxy

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic:/etc/traefik/dynamic"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"


networks:
  haproxy:
    external: true